apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-env-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: virtual-env-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - virtual-env-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - env.alibaba.com
    resources:
      - '*'
      - virtualenvironments
    verbs:
      - '*'
  - apiGroups:
      - networking.istio.io
    resources:
      - envoyfilters
      - destinationrules
      - virtualservices
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: virtual-env-operator
subjects:
  - kind: ServiceAccount
    name: virtual-env-operator
roleRef:
  kind: Role
  name: virtual-env-operator
  apiGroup: rbac.authorization.k8s.io
